// Generated by CoffeeScript 1.10.0
(function() {
  var app, express, metrics;

  express = require('express');

  app = express();

  metrics = require('./metrics');

  app.set('port', 1889);

  app.set('views', __dirname + "/../views");

  app.set('view engine', 'jade');

  app.use('/', express["static"](__dirname + "/../public"));

  app.use(require('body-parser')());

  app.get('/login', function(req, res) {
    return res.render('login');
  });

  app.get('/', function(req, res) {
    return res.render('index', {
      locals: {
        title: 'My ECE test page'
      }
    });
  });

  app.get('/metrics.json', function(req, res) {
    return res.status(200).json(metrics.get());
  });

  app.get('/hello/:name', function(req, res) {
    return res.status(200).send(req.params.name);
  });

  app.post('/metric/:id.json', function(req, res) {
    return metrics.save(req.params.id, req.body, function(err) {
      if (err) {
        return res.status(500).json(err);
      } else {
        return res.status(200).send("Metrics saved");
      }
    });
  });

  app.listen(app.get('port'), function() {
    return console.log("listening on " + (app.get('port')));
  });

}).call(this);

//# sourceMappingURL=app.js.map
