// Generated by CoffeeScript 1.10.0
(function() {
  var db, levelup;

  levelup = require('levelup');

  db = levelup('./db');

  module.exports = {
    get: function(value) {
      return console.log("GET METHOD CALLED, value = " + value);
    }
  };

  db.put('name', 'LevelUP', function(err) {
    if (err) {
      return console.log('Ooops!', err);
    }
    db.get('name', function(err, value) {
      if (err) {
        return console.log('Ooops!', err);
      }
      console.log('name=' + value);
    });
    return;
    return {

      /*
      `save(id, metrics, cb)`
      ------------------------
      Save some metrics with a given id
      
      Parameters:
      `id`: An integer defining a batch of metrics
      `metrics`: An array of objects with a timestamp and a value
      `callback`: Callback function takes an error or null as parameter
       */
      save: function(id, metrics, callback) {
        var i, len, m, timestamp, value, ws;
        ws = db.createWriteStream();
        ws.on('error', callback);
        ws.on('close', callback);
        for (i = 0, len = metrics.length; i < len; i++) {
          m = metrics[i];
          timestamp = m.timestamp, value = m.value;
          ws.write({
            key: "metric:" + id + ":" + timestamp,
            value: value
          });
        }
        return ws.end();
      }

      /*
       */
    };
  });

}).call(this);

//# sourceMappingURL=metrics.js.map
