// Generated by CoffeeScript 1.10.0
(function() {
  var db;

  db = require('./db')(__dirname + "/../db/user_db");

  module.exports = {
    get: function(callback) {
      var rs, users;
      users = [];
      rs = db.createReadStream({
        gte: "user:a",
        lte: "user:zzzzzzzzzzzzzzzzzzz"
      });
      rs.on('data', function(data) {
        var key, value;
        key = data.key.split(":");
        value = data.value.split(":");
        users.push({
          user: value[1],
          pass: value[2]
        });
        return users;
      });
      rs.on('error', function() {
        return callback(null);
      });
      return rs.on('close', function() {
        return callback(null, users);
      });
    },
    save: function(user, pass, callback) {
      var ws;
      ws = db.createWriteStream();
      ws.write({
        key: "user:" + user,
        value: "user:" + user + ":" + pass
      });
      console.log("Check login | User '" + user + "' is registered.");
      ws.on('error', callback);
      ws.on('close', callback);
      return ws.end();
    },
    check: function(user, callback) {
      var rs;
      rs = db.createReadStream({
        gte: "user:" + user,
        lte: "user:" + user
      });
      rs.on('data', function(data) {
        var value;
        value = data.value.split(":");
        return user = {
          user: value[1],
          pass: value[2]
        };
      });
      rs.on('error', callback);
      return rs.on('close', function() {
        return callback(null, user);
      });
    }
  };

}).call(this);

//# sourceMappingURL=users.js.map
